### ISSUE TITLE
Rebuilding pushed games...

### ISSUE THREAD

**Issue by probityrules** [SpringRoll/SpringRollConnect#1]
Is there a way to force a game to rebuild?

For example, if we post a game, and then later one of the libraries is updated, can we rebuild the game from the Spring Roll Connect web interface so that the games' dependencies are updated without requiring us to push a new version of the game?

**Comment by bigtimebuddy** [comment]
The rebuilding of a commit happens through Jenkins. I'll email you instructions of how to do this.
