### ISSUE TITLE
Add releases button doesn't add release to game

### ISSUE THREAD

**Issue by xoorath** [SpringRoll/SpringRollConnect#15]
It seems the url isn't being populated in the database:

![image](https://cloud.githubusercontent.com/assets/769014/22528209/49118b4e-e8a0-11e6-82ed-9a7307b2e489.png)

And the releases array isn't being poulated, meaning I can't see or modify my release in springroll connect.

![image](https://cloud.githubusercontent.com/assets/769014/22528228/599e6d06-e8a0-11e6-86c6-3a17fac7cd3e.png)

Here's what I see before adding a release:
![image](https://cloud.githubusercontent.com/assets/769014/22528291/9c76466c-e8a0-11e6-8b01-6446e2fca92d.png)

How I create the new release:
![image](https://cloud.githubusercontent.com/assets/769014/22528312/b6bc2712-e8a0-11e6-8bcb-d92c130bd432.png)

And after the release is "created":
![image](https://cloud.githubusercontent.com/assets/769014/22528316/c1fdafba-e8a0-11e6-848e-5ecf660edb40.png)

**Comment by chipbell4** [comment]
Just verified that this has been fixed (at least as of 1.7.0)

**Comment by chipbell4** [comment]
Going to go ahead and close, but feel free to reopen if you're still seeing a problem
