### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by xoorath** [SpringRoll/SpringRollConnect#6]
Hey,

I'd like to suggest adding to the setup instructions to make it a bit more clear. I'm not sure if this is because I'm developing on windows or have some specific environment variables, but to get everything setup correctly I had to do the following not included in the setup:

`npm install --python=2.7`

The python version was needed to successfully install one of the depends of marky markdown.

The full path throwing the error is at
`SpringRollConnect\node_modules\marky-markdown\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma`

and the full error text including the python version complaint was:

```
C:\Users\jthomson\Documents\GitHub\SpringRollConnect\node_modules\marky-markdown\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma {git}{hg}
{lamb} if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.5.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:121:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:110:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jthomson\Documents\GitHub\SpringRollConnect\node_modules\marky-markdown\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jthomson\Documents\GitHub\SpringRollConnect\npm-debug.log
```

Note that after installing with an error I was still able to run the app and get into the DB but after doing the initial setup the server would tell me about an issue with marky markdown, which is why I went back and fixed the issue as stated above.

The only other thing I'd say from a user experience standpoint is that you probably don't need to spam `SpringRoll API running on http://localhost:3000` to the server console and that the initial setup form probably shouldn't clear out all the values on a form error - it's probably long enough to justify holding those values so users don't have to re-enter them.

cheers :)

edit: I understand the point of the "spam" now.

**Comment by chipbell4** [comment]
@xoorath We've finally got a `feature/docker` branch up that should hopefully simplify some of the set up for you moving forward. Take a look if you get a chance and let me know if that helps.

**Comment by chipbell4** [comment]
An update: This is now merged into master. I'm going to close this for now, but feel free to open it back up if you run into any more issues.
